using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Numerics;
using System.Text;
using PicoGK;

namespace Impetus.Geometry;

/// <summary>
/// Material/color definition for 3MF export.
/// </summary>
public record MaterialInfo(string Name, string ColorHex, double Opacity = 1.0);

/// <summary>
/// Export PicoGK meshes to interchange formats. PicoGK only writes STL; 3MF is
/// built here so slicers (e.g. Anycubic Kobra S1) get explicit millimeter units.
/// </summary>
public static class MeshExport
{
    public readonly record struct ThreeMfPart(string Name, Mesh Mesh, MaterialInfo? Material = null);

    public static void SaveMeshFiles(Mesh msh, string strStlPath, string strThreeMfPath, string strTitle)
    {
        msh.SaveToStlFile(strStlPath);
        SaveToThreeMfFile(strThreeMfPath, strTitle, new ThreeMfPart(strTitle, msh));
    }

    public static void SaveAssemblyMeshFiles(
        Mesh mshCombined,
        IReadOnlyList<ThreeMfPart> aoParts,
        string strStlPath,
        string strThreeMfPath,
        string strTitle)
    {
        mshCombined.SaveToStlFile(strStlPath);
        SaveToThreeMfFile(strThreeMfPath, strTitle, aoParts);
    }

    /// <summary>Save mesh to OBJ format (for viewers that don't support 3MF).</summary>
    public static void SaveToObjFile(Mesh msh, string strPath, string strObjectName = "mesh")
    {
        using StreamWriter writer = new(File.Create(strPath), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        writer.WriteLine($"# OBJ file generated by Impetus");
        writer.WriteLine($"# Object: {strObjectName}");
        writer.WriteLine($"o {strObjectName}");

        // Write vertices
        int nVerts = msh.nVertexCount();
        for (int i = 0; i < nVerts; i++)
        {
            Vector3 vec = msh.vecVertexAt(i);
            writer.WriteLine($"v {vec.X.ToString("G9", CultureInfo.InvariantCulture)} {vec.Y.ToString("G9", CultureInfo.InvariantCulture)} {vec.Z.ToString("G9", CultureInfo.InvariantCulture)}");
        }

        // Write faces (triangles)
        int nTris = msh.nTriangleCount();
        for (int i = 0; i < nTris; i++)
        {
            Triangle tri = msh.oTriangleAt(i);
            // OBJ uses 1-based indexing
            writer.WriteLine($"f {tri.A + 1} {tri.B + 1} {tri.C + 1}");
        }
    }

    public static void SaveToThreeMfFile(Mesh msh, string strPath, string strTitle)
        => SaveToThreeMfFile(strPath, strTitle, new ThreeMfPart(strTitle, msh));

    public static void SaveToThreeMfFile(string strPath, string strTitle, params ThreeMfPart[] aoParts)
        => SaveToThreeMfFile(strPath, strTitle, (IReadOnlyList<ThreeMfPart>)aoParts);

    public static void SaveToThreeMfFile(string strPath, string strTitle, IReadOnlyList<ThreeMfPart> aoParts)
    {
        if (aoParts.Count == 0)
            throw new ArgumentException("At least one 3MF part is required.", nameof(aoParts));

        WriteThreeMfArchive(strPath, BuildModelXml(strTitle, aoParts));
    }

    static string BuildModelXml(string strTitle, IReadOnlyList<ThreeMfPart> aoParts)
    {
        var sb = new StringBuilder(4096);
        sb.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.Append("<model unit=\"millimeter\" xml:lang=\"und-US\" xmlns=\"http://schemas.microsoft.com/3dmanufacturing/core/2015/02\" xmlns:m=\"http://schemas.microsoft.com/3dmanufacturing/material/2015/02\">");

        string strNow = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
        sb.Append("<metadata name=\"Title\">").Append(EscapeXml(strTitle)).Append("</metadata>");
        sb.Append("<metadata name=\"Application\">Impetus computational thruster design</metadata>");
        sb.Append("<metadata name=\"CreationDate\">").Append(strNow).Append("</metadata>");
        sb.Append("<metadata name=\"Designer\">Impetus</metadata>");
        sb.Append("<metadata name=\"Description\">Rocket engine display geometry; units millimeters; not for hot fire in plastic.</metadata>");

        sb.Append("<resources>");

        // Add materials if any parts have materials
        int nMaterialId = 0;
        var aoMaterialIds = new Dictionary<string, int>();
        for (int i = 0; i < aoParts.Count; i++)
        {
            if (aoParts[i].Material is MaterialInfo oMat && !aoMaterialIds.ContainsKey(oMat.ColorHex))
            {
                nMaterialId++;
                aoMaterialIds[oMat.ColorHex] = nMaterialId;
                sb.Append("<material id=\"").Append(nMaterialId).Append("\" name=\"").Append(EscapeXml(oMat.Name)).Append("\">");
                sb.Append("<m:base><m:color><m:red>").Append(GetColorComponent(oMat.ColorHex, 0))
                    .Append("</m:red><m:green>").Append(GetColorComponent(oMat.ColorHex, 1))
                    .Append("</m:green><m:blue>").Append(GetColorComponent(oMat.ColorHex, 2))
                    .Append("</m:blue><m:alpha>").Append(oMat.Opacity.ToString("G9", CultureInfo.InvariantCulture))
                    .Append("</m:alpha></m:color></m:base></material>");
            }
        }

        // Add objects
        for (int i = 0; i < aoParts.Count; i++)
        {
            int nId = i + 1;
            ThreeMfPart oPart = aoParts[i];
            sb.Append("<object id=\"").Append(nId).Append("\" type=\"model\" name=\"")
                .Append(EscapeXml(oPart.Name)).Append("\"><mesh><vertices>");
            AppendVertices(sb, oPart.Mesh);
            sb.Append("</vertices><triangles>");
            AppendTriangles(sb, oPart.Mesh);
            sb.Append("</triangles>");

            // Add material reference if this part has a material
            if (oPart.Material is MaterialInfo oMat && aoMaterialIds.TryGetValue(oMat.ColorHex, out int nMatId))
            {
                sb.Append("<components><component materialid=\"").Append(nMatId).Append("\"><object objectid=\"").Append(nId).Append("\"/></component></components>");
            }

            sb.Append("</mesh></object>");
        }
        sb.Append("</resources><build>");
        for (int i = 0; i < aoParts.Count; i++)
            sb.Append("<item objectid=\"").Append(i + 1).Append("\"/>");
        sb.Append("</build></model>");
        return sb.ToString();
    }

    static int GetColorComponent(string strHex, int nIndex)
    {
        // Parse hex color like "#FF0000" and return 0-255 value for component (0=R, 1=G, 2=B)
        string strValue = strHex.TrimStart('#').Substring(nIndex * 2, 2);
        return Convert.ToInt32(strValue, 16);
    }

    static void AppendVertices(StringBuilder sb, Mesh msh)
    {
        int nVerts = msh.nVertexCount();
        for (int i = 0; i < nVerts; i++)
        {
            Vector3 vec = msh.vecVertexAt(i);
            sb.Append("<vertex x=\"")
                .Append(vec.X.ToString("G9", CultureInfo.InvariantCulture))
                .Append("\" y=\"")
                .Append(vec.Y.ToString("G9", CultureInfo.InvariantCulture))
                .Append("\" z=\"")
                .Append(vec.Z.ToString("G9", CultureInfo.InvariantCulture))
                .Append("\"/>");
        }
    }

    static void AppendTriangles(StringBuilder sb, Mesh msh)
    {
        int nTris = msh.nTriangleCount();
        for (int i = 0; i < nTris; i++)
        {
            Triangle tri = msh.oTriangleAt(i);
            sb.Append("<triangle v1=\"")
                .Append(tri.A)
                .Append("\" v2=\"")
                .Append(tri.B)
                .Append("\" v3=\"")
                .Append(tri.C)
                .Append("\"/>");
        }
    }

    static string EscapeXml(string str)
        => str.Replace("&", "&amp;", StringComparison.Ordinal)
              .Replace("<", "&lt;", StringComparison.Ordinal)
              .Replace(">", "&gt;", StringComparison.Ordinal)
              .Replace("\"", "&quot;", StringComparison.Ordinal);

    static void WriteThreeMfArchive(string strPath, string strModelXml)
    {
        if (File.Exists(strPath))
            File.Delete(strPath);

        using FileStream oFile = File.Create(strPath);
        using var zip = new ZipArchive(oFile, ZipArchiveMode.Create);

        AddZipEntry(zip, "[Content_Types].xml",
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
              <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
              <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
            </Types>
            """);

        AddZipEntry(zip, "_rels/.rels",
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
              <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
            </Relationships>
            """);

        AddZipEntry(zip, "3D/3dmodel.model", strModelXml);
    }

    static void AddZipEntry(ZipArchive zip, string strName, string strContent)
    {
        ZipArchiveEntry oEntry = zip.CreateEntry(strName, CompressionLevel.Optimal);
        using StreamWriter writer = new(oEntry.Open(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        writer.Write(strContent.Trim());
    }
}
