using System.Text;
using Impetus.Physics;

namespace Impetus.Reporting;

/// <summary>
/// Generates pre-hot-fire checklist from validation results.
/// </summary>
public static class ChecklistReport
{
    public static string Build(EngineDesign oDesign, ValidationResult oValidation)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"# {oDesign.Spec.Name} - Pre-Hot-Fire Checklist");
        sb.AppendLine();
        sb.AppendLine($"Generated by Impetus on {DateTime.Now:yyyy-MM-dd HH:mm}.");
        sb.AppendLine();
        sb.AppendLine("## Status Overview");
        sb.AppendLine();
        sb.AppendLine($"- **Verdict:** {oValidation.Verdict}");
        sb.AppendLine($"- **Summary:** {oValidation.VerdictSummary}");
        sb.AppendLine($"- **Total Checks:** {oValidation.Checks.Count}");
        sb.AppendLine($"- **Passed:** {oValidation.Checks.Count(c => c.Status == CheckStatus.Pass)}");
        sb.AppendLine($"- **Warnings:** {oValidation.Checks.Count(c => c.Status == CheckStatus.Warn)}");
        sb.AppendLine($"- **Failed:** {oValidation.Checks.Count(c => c.Status == CheckStatus.Fail)}");
        sb.AppendLine();

        sb.AppendLine("## Pre-Hot-Fire Checklist");
        sb.AppendLine();
        sb.AppendLine("### Design Validation");
        sb.AppendLine();

        foreach (var check in oValidation.Checks)
        {
            string strStatus = check.Status switch
            {
                CheckStatus.Pass => "[x]",
                CheckStatus.Warn => "[!]",
                CheckStatus.Fail => "[ ]",
                _ => "[?]"
            };

            string strSpecField = check.SpecField is not null ? $" (spec field: `{check.SpecField}`)" : "";
            sb.AppendLine($"{strStatus} **{check.Name}**{strSpecField}");
            sb.AppendLine($"   - {check.Detail}");
            sb.AppendLine($"   - Action: {check.Action}");
            sb.AppendLine();
        }

        sb.AppendLine("### Feed System Requirements");
        sb.AppendLine();
        sb.AppendLine($"- **Fuel tank pressure:** {oValidation.Feed.FuelTankPressureBar:F1} bar");
        sb.AppendLine($"- **Oxidizer tank pressure:** {oValidation.Feed.OxTankPressureBar:F1} bar");
        sb.AppendLine($"- **Feed line diameter:** {oValidation.Feed.FeedLineDiameterMM:F1} mm");
        sb.AppendLine($"- **Fuel mass required:** {oValidation.Feed.FuelMassKg:F2} kg");
        sb.AppendLine($"- **Oxidizer mass required:** {oValidation.Feed.OxMassKg:F2} kg");
        sb.AppendLine($"- **Burn duration:** {oValidation.Feed.BurnDurationS:F1} s");
        sb.AppendLine();

        sb.AppendLine("### Hardware Checklist");
        sb.AppendLine();
        sb.AppendLine("- [ ] Engine hardware manufactured to spec");
        sb.AppendLine("- [ ] Cooling channels verified (flow test)");
        sb.AppendLine("- [ ] Injector plate installed and sealed");
        sb.AppendLine("- [ ] Mounting flange aligned");
        sb.AppendLine("- [ ] Feed system pressure-rated to required pressure");
        sb.AppendLine("- [ ] Tank volumes sufficient for required propellant mass");
        sb.AppendLine("- [ ] Pressure transducers installed");
        sb.AppendLine("- [ ] Thermocouples installed (chamber, coolant inlet/outlet)");
        sb.AppendLine("- [ ] Thrust measurement system calibrated");
        sb.AppendLine("- [ ] Remote firing system operational");
        sb.AppendLine("- [ ] Fire suppression system ready");
        sb.AppendLine("- [ ] Personnel clear of test area");
        sb.AppendLine("- [ ] Burst disks installed");
        sb.AppendLine("- [ ] Emergency shutdown procedure reviewed");
        sb.AppendLine();

        sb.AppendLine("### Test Procedure");
        sb.AppendLine();
        sb.AppendLine("1. **Cold flow test:** Verify propellant flow rates and pressure drops");
        sb.AppendLine("2. **Short duration test (1-2s):** Verify ignition and basic operation");
        sb.AppendLine("3. **Medium duration test (5s):** Verify thermal stability");
        sb.AppendLine("4. **Full duration test:** Verify performance and endurance");
        sb.AppendLine();

        sb.AppendLine("### Data Collection");
        sb.AppendLine();
        sb.AppendLine("- [ ] Chamber pressure vs time");
        sb.AppendLine("- [ ] Tank pressures vs time");
        sb.AppendLine("- [ ] Coolant inlet/outlet temperatures vs time");
        sb.AppendLine("- [ ] Thrust vs time");
        sb.AppendLine("- [ ] Video recording");
        sb.AppendLine();

        sb.AppendLine("## Post-Hot-Fire Actions");
        sb.AppendLine();
        sb.AppendLine("- [ ] Inspect engine for damage");
        sb.AppendLine("- [ ] Review data for anomalies");
        sb.AppendLine("- [ ] Compare measured performance to predictions");
        sb.AppendLine("- [ ] Document findings in test report");
        sb.AppendLine("- [ ] Update spec if performance differs significantly");
        sb.AppendLine();

        return sb.ToString();
    }

    public static void SaveChecklist(EngineDesign oDesign, ValidationResult oValidation, string strOutDir)
    {
        string strChecklist = Build(oDesign, oValidation);
        File.WriteAllText(Path.Combine(strOutDir, "checklist.md"), strChecklist);
    }
}
