using System.Globalization;
using System.Text;
using Impetus.Cfd;
using Impetus.Physics;

namespace Impetus.Reporting;

/// <summary>Human-readable design dossier: console summary + markdown file.</summary>
public static class DesignReport
{
    public static string Build(EngineDesign o, ThermalResult oTherm)
    {
        EngineSpec s = o.Spec;
        StringBuilder sb = new();

        sb.AppendLine($"# {s.Name} - Engine Design Report");
        sb.AppendLine();
        sb.AppendLine($"Generated by Impetus on {DateTime.Now:yyyy-MM-dd HH:mm}.");
        sb.AppendLine();
        sb.AppendLine("## Specification");
        sb.AppendLine();
        sb.AppendLine($"| Input | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Propellants | {o.Gas.Name} |");
        sb.AppendLine($"| Thrust (target) | {F(s.ThrustN, "F0")} N |");
        sb.AppendLine($"| Chamber pressure | {F(s.ChamberPressureBar, "F1")} bar |");
        sb.AppendLine($"| Ambient pressure | {F(s.AmbientPressureBar, "F3")} bar |");
        sb.AppendLine($"| O/F ratio | {F(s.OfRatio, "F2")} |");
        sb.AppendLine($"| Contraction ratio | {F(s.ContractionRatio, "F1")} |");
        sb.AppendLine();
        sb.AppendLine("## Performance (ideal rocket theory)");
        sb.AppendLine();
        sb.AppendLine($"| Quantity | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Specific impulse (design ambient) | {F(o.IspSeaLevelS, "F1")} s |");
        sb.AppendLine($"| Specific impulse (vacuum) | {F(o.IspVacuumS, "F1")} s |");
        sb.AppendLine($"| Characteristic velocity c* | {F(o.CStar, "F0")} m/s |");
        sb.AppendLine($"| Thrust coefficient CF | {F(o.ThrustCoeff, "F3")} |");
        sb.AppendLine($"| Exhaust velocity | {F(o.ExhaustVelocity, "F0")} m/s |");
        sb.AppendLine($"| Mass flow total | {F(o.MassFlow, "F3")} kg/s |");
        sb.AppendLine($"| - fuel | {F(o.MassFlowFuel, "F3")} kg/s |");
        sb.AppendLine($"| - oxidizer | {F(o.MassFlowOx, "F3")} kg/s |");
        sb.AppendLine($"| Expansion ratio Ae/At | {F(o.ExpansionRatio, "F2")} |");
        sb.AppendLine($"| Exit Mach | {F(o.ExitMach, "F2")} |");
        sb.AppendLine($"| Exit pressure | {F(o.ExitPressure / 1e5, "F3")} bar |");
        sb.AppendLine();
        sb.AppendLine("## Geometry");
        sb.AppendLine();
        sb.AppendLine($"| Dimension | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Throat diameter | {MM(o.ThroatRadius * 2)} mm |");
        sb.AppendLine($"| Exit diameter | {MM(o.ExitRadius * 2)} mm |");
        sb.AppendLine($"| Chamber diameter | {MM(o.ChamberRadius * 2)} mm |");
        sb.AppendLine($"| Contraction ratio (applied) | {F(o.ContractionRatioUsed, "F2")} |");
        sb.AppendLine($"| Chamber cylinder length | {MM(o.ChamberCylinderLength)} mm |");
        sb.AppendLine($"| Bell length ({F(s.BellFraction * 100, "F0")}% Rao) | {MM(o.BellLength)} mm |");
        sb.AppendLine($"| Bell angles theta_n / theta_e | {DEG(o.BellThetaN)} / {DEG(o.BellThetaE)} deg |");
        sb.AppendLine($"| Chamber volume (L* = {F(o.Gas.LStar, "F2")} m) | {F(o.ChamberVolume * 1e6, "F1")} cm3 |");
        sb.AppendLine();
        sb.AppendLine("## Thermal (Bartz) & regenerative cooling");
        sb.AppendLine();
        sb.AppendLine($"| Quantity | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Peak (throat) heat flux | {F(oTherm.ThroatHeatFlux / 1e6, "F1")} MW/m2 |");
        sb.AppendLine($"| Total regen heat load | {F(oTherm.TotalHeatLoad / 1e3, "F1")} kW |");
        sb.AppendLine($"| Peak gas-side wall temperature | {F(oTherm.PeakWallTempK, "F0")} K |");
        sb.AppendLine($"| Throat wall temperature (1D regen) | {F(oTherm.ThroatWallTempK, "F0")} K |");
        sb.AppendLine($"| Coolant inlet / outlet | {F(oTherm.CoolantInletTempK, "F0")} / {F(oTherm.CoolantOutletTempK, "F0")} K |");
        sb.AppendLine($"| Coolant (fuel) temperature rise | {F(oTherm.CoolantTempRise, "F0")} K |");
        sb.AppendLine($"| Coolant velocity in channels | {F(oTherm.CoolantVelocity, "F1")} m/s |");
        sb.AppendLine($"| Channel pressure drop | {F(oTherm.ChannelPressureDropPa / 1e5, "F2")} bar |");
        sb.AppendLine($"| Channels | {s.Cooling.Count} x {F(s.Cooling.DiameterMM, "F1")} mm, {F(s.Cooling.HelixTurns, "F1")} turns |");
        sb.AppendLine();
        sb.AppendLine("## Injector (showerhead)");
        sb.AppendLine();
        sb.AppendLine($"| Quantity | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Pressure drop | {F(o.InjectorDeltaP / 1e5, "F1")} bar (20% Pc) |");
        sb.AppendLine($"| Fuel orifices | {o.FuelOrificeCount} x {F(o.FuelOrificeDiameter * 1000, "F2")} mm |");
        sb.AppendLine($"| Oxidizer orifices | {o.OxOrificeCount} x {F(o.OxOrificeDiameter * 1000, "F2")} mm |");
        sb.AppendLine();

        return sb.ToString();
    }

    public static string CfdSection(EngineDesign o, CfdResult oCfd, ThermalResult? oTherm = null)
    {
        StringBuilder sb = new();
        double fDevThrust = 100.0 * (oCfd.ThrustN - o.Spec.ThrustN) / o.Spec.ThrustN;
        double fDevMdot = 100.0 * (oCfd.MassFlow - o.MassFlow) / o.MassFlow;
        double fDevMach = 100.0 * (oCfd.ExitMachAvg - o.ExitMach) / o.ExitMach;

        sb.AppendLine("## Virtual test (SU2 CFD, axisymmetric RANS-SST)");
        sb.AppendLine();
        double fWallBc = oTherm?.ThroatWallTempK ?? oTherm?.PeakWallTempK ?? ThermalModel.AssumedRegenWallTempK;
        if (double.IsNaN(fWallBc) || fWallBc <= 0)
            fWallBc = ThermalModel.AssumedRegenWallTempK;
        sb.AppendLine($"Converged: {(oCfd.Converged ? "yes" : "no (check su2.log)")}, " +
                      $"iterations: {oCfd.Iterations}. " +
                      $"Wall BC: isothermal {F(fWallBc, "F0")} K (1D regen throat wall).");
        sb.AppendLine();
        sb.AppendLine($"| Quantity | Analytic | CFD | Deviation |");
        sb.AppendLine($"|---|---|---|---|");
        sb.AppendLine($"| Thrust | {F(o.Spec.ThrustN, "F1")} N | {F(oCfd.ThrustN, "F1")} N | {F(fDevThrust, "+0.0;-0.0")}% |");
        sb.AppendLine($"| Mass flow | {F(o.MassFlow, "F3")} kg/s | {F(oCfd.MassFlow, "F3")} kg/s | {F(fDevMdot, "+0.0;-0.0")}% |");
        sb.AppendLine($"| Exit Mach (area avg) | {F(o.ExitMach, "F2")} | {F(oCfd.ExitMachAvg, "F2")} | {F(fDevMach, "+0.0;-0.0")}% |");
        sb.AppendLine($"| Exit pressure (area avg) | {F(o.ExitPressure / 1e5, "F3")} bar | {F(oCfd.ExitPressureAvg / 1e5, "F3")} bar | |");

        if (oTherm is not null && oCfd.ThroatWallHeatFluxMWm2 is double fQcfd)
        {
            double fQBartz = oTherm.ThroatHeatFlux / 1e6;
            double fDevQ = 100.0 * (fQcfd - fQBartz) / Math.Max(fQBartz, 1e-12);
            sb.AppendLine($"| Throat wall heat flux | {F(fQBartz, "F1")} MW/m2 (Bartz) | {F(fQcfd, "F1")} MW/m2 | {F(fDevQ, "+0.0;-0.0")}% |");
        }
        else if (oTherm is not null)
        {
            sb.AppendLine($"| Throat wall heat flux (Bartz) | {F(oTherm.ThroatHeatFlux / 1e6, "F1")} MW/m2 | (not in surface CSV) | |");
        }

        sb.AppendLine();
        sb.AppendLine("Flow field: open `cfd/flow.vtu` in ParaView. " +
                      "Solver log: `cfd/su2.log`. Wall heat flux from `surface_flow.csv` when present.");
        sb.AppendLine();
        return sb.ToString();
    }

    public static void PrintSummary(EngineDesign o, ThermalResult oTherm)
    {
        Console.WriteLine();
        Console.WriteLine($"  == {o.Spec.Name} ==  {o.Gas.Name}");
        Console.WriteLine($"  Thrust {o.Spec.ThrustN:F0} N @ {o.Spec.ChamberPressureBar:F0} bar   " +
                          $"Isp {o.IspSeaLevelS:F1} s (SL) / {o.IspVacuumS:F1} s (vac)");
        Console.WriteLine($"  Throat D {o.ThroatRadius * 2000:F1} mm   Exit D {o.ExitRadius * 2000:F1} mm   " +
                          $"eps {o.ExpansionRatio:F2}   mdot {o.MassFlow:F3} kg/s");
        Console.WriteLine($"  Chamber D {o.ChamberRadius * 2000:F1} mm   q_throat {oTherm.ThroatHeatFlux / 1e6:F1} MW/m2   " +
                          $"coolant dT {oTherm.CoolantTempRise:F0} K");
        Console.WriteLine();
    }

    static string F(double f, string strFmt) => f.ToString(strFmt, CultureInfo.InvariantCulture);
    static string MM(double fMeters) => F(fMeters * 1000.0, "F1");
    static string DEG(double fRad) => F(fRad * 180.0 / Math.PI, "F1");
}
