using System.Globalization;
using System.Text;
using Impetus.Physics;

namespace Impetus.Reporting;

public static class ValidationReport
{
    public static string BuildSection(EngineDesign o, ValidationResult oVal)
    {
        StringBuilder sb = new();
        sb.AppendLine("## Virtual validation (pre-physical-test gate)");
        sb.AppendLine();
        sb.AppendLine($"**Verdict: `{oVal.Verdict}`** — {oVal.VerdictSummary}");
        sb.AppendLine();
        sb.AppendLine("Impetus cannot fire an engine. These checks substitute for the first");
        sb.AppendLine("stages of a test campaign: catch bad cooling, injector, and nozzle designs");
        sb.AppendLine("*before* metal is cut. Physical hot fire still required to prove combustion.");
        sb.AppendLine();
        sb.AppendLine("| Check | Status | Detail |");
        sb.AppendLine("|---|---|---|");
        foreach (ValidationCheck oCheck in oVal.Checks)
        {
            sb.AppendLine($"| {oCheck.Name} | {StatusLabel(oCheck.Status)} | {oCheck.Detail} |");
        }
        sb.AppendLine();
        sb.AppendLine("### Recommended actions");
        sb.AppendLine();
        foreach (ValidationCheck oCheck in oVal.Checks.Where(c => c.Status != CheckStatus.Pass))
        {
            sb.AppendLine($"- **{oCheck.Name}** ({StatusLabel(oCheck.Status)}): {oCheck.Action}");
        }
        if (oVal.Checks.All(c => c.Status == CheckStatus.Pass))
            sb.AppendLine("- All virtual checks passed — see `hotfire-plan.md` for the physical test ladder.");
        sb.AppendLine();
        sb.AppendLine("### Feed system sizing (for test stand)");
        sb.AppendLine();
        FeedSystemSizing f = oVal.Feed;
        sb.AppendLine($"| Item | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Burn duration (assumed) | {F(f.BurnDurationS, "F1")} s |");
        sb.AppendLine($"| Fuel mass required | {F(f.FuelMassKg, "F2")} kg |");
        sb.AppendLine($"| Oxidizer mass required | {F(f.OxMassKg, "F2")} kg |");
        sb.AppendLine($"| Min fuel tank pressure | {F(f.FuelTankPressureBar, "F1")} bar |");
        sb.AppendLine($"| Min oxidizer tank pressure | {F(f.OxTankPressureBar, "F1")} bar |");
        sb.AppendLine($"| Suggested feed line ID | Ø{F(f.FeedLineDiameterMM, "F1")} mm |");
        sb.AppendLine();
        sb.AppendLine("Includes Pc + injector Δp + line/valve losses + 1 bar margin.");
        sb.AppendLine();
        sb.AppendLine("### Materials (flight intent)");
        sb.AppendLine();
        sb.AppendLine("| Component | Material | Process |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine("| Chamber liner + regen channels | CuCrZr | LPBF + HIP |");
        sb.AppendLine("| Nozzle bell (uncooled) | Inconel 718 | LPBF or machined |");
        sb.AppendLine("| Injector plate | Inconel 718 | LPBF or machined |");
        sb.AppendLine("| Flange / structural | Al 6061 or Ti-6Al-4V | machined |");
        sb.AppendLine();
        sb.AppendLine("FDM plastic (`engine.stl`) is for display only — not for hot fire.");
        sb.AppendLine();
        return sb.ToString();
    }

    public static string BuildHotFirePlan(EngineDesign o, ThermalResult oTherm, ValidationResult oVal)
    {
        EngineSpec s = o.Spec;
        FeedSystemSizing f = oVal.Feed;
        StringBuilder sb = new();

        sb.AppendLine($"# {s.Name} — Hot-Fire Test Plan");
        sb.AppendLine();
        sb.AppendLine($"Generated by Impetus on {DateTime.Now:yyyy-MM-dd HH:mm}.");
        sb.AppendLine();
        sb.AppendLine("> **Safety:** Rocket engine testing is hazardous. This document is an");
        sb.AppendLine("> engineering checklist, not a safety certification. Operate only with");
        sb.AppendLine("> qualified personnel, remote actuation, blast shielding, fire suppression,");
        sb.AppendLine("> and compliance with local law.");
        sb.AppendLine();
        sb.AppendLine($"Virtual gate verdict: **`{oVal.Verdict}`**");
        sb.AppendLine();
        sb.AppendLine("## Why virtual testing comes first");
        sb.AppendLine();
        sb.AppendLine("A better engine is built by iterating cheap virtual tests before expensive");
        sb.AppendLine("physical ones:");
        sb.AppendLine();
        sb.AppendLine("1. **Analytic sizing** (instant) — thrust, dimensions, cooling estimate");
        sb.AppendLine("2. **Virtual validation** (instant) — pass/fail gates on cooling, injector, expansion");
        sb.AppendLine("3. **CFD virtual test** (~30 min) — nozzle thrust/Mach vs analytic");
        sb.AppendLine("4. **Cold flow** (physical) — prove feed pressures, flows, no leaks");
        sb.AppendLine("5. **Hot fire** (physical) — prove combustion, measure real thrust & Pc");
        sb.AppendLine();
        sb.AppendLine("Impetus covers steps 1–3. Steps 4–5 require a test stand you build or access.");
        sb.AppendLine();
        sb.AppendLine("## Pre-requisites (do not skip)");
        sb.AppendLine();
        sb.AppendLine("- [ ] Virtual verdict is `VIRTUAL_OK` or `VIRTUAL_OK_WITH_WARNINGS` (not `ITERATE_DESIGN`)");
        sb.AppendLine("- [ ] SU2 CFD run completed and thrust deviation < 10%");
        sb.AppendLine("- [ ] Engine printed in **metal** (CuCrZr/Inconel), not FDM plastic");
        sb.AppendLine("- [ ] Feed tanks rated above set pressures (see feed table in `report.md`)");
        sb.AppendLine("- [ ] Remote-operated solenoid valves on both propellant lines");
        sb.AppendLine("- [ ] Burst disks or relief valves on feed lines");
        sb.AppendLine("- [ ] Flame deflector, blast shield, fire suppression");
        sb.AppendLine("- [ ] Legal clearance for propellant storage and engine testing");
        sb.AppendLine();
        sb.AppendLine("## Hardware to build / procure");
        sb.AppendLine();
        sb.AppendLine($"| Item | Spec |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Engine | {s.Name}, Ø{MM(o.ChamberRadius * 2)} mm chamber, {F(s.ThrustN, "F0")} N target |");
        sb.AppendLine($"| Fuel tank | ≥ {F(f.FuelMassKg * 1.5, "F2")} kg capacity, ≥ {F(f.FuelTankPressureBar, "F1")} bar |");
        sb.AppendLine($"| Oxidizer tank | ≥ {F(f.OxMassKg * 1.5, "F2")} kg capacity, ≥ {F(f.OxTankPressureBar, "F1")} bar |");
        sb.AppendLine($"| Feed lines | Ø{F(f.FeedLineDiameterMM, "F1")} mm ID, ≤ 2 m run length |");
        sb.AppendLine($"| Thrust stand | Load cell ≥ {F(s.ThrustN * 3, "F0")} N capacity |");
        sb.AppendLine($"| Ignition | Pyrotechnic or spark igniter in igniter port (geometry included) |");
        sb.AppendLine();
        sb.AppendLine("## Instrumentation");
        sb.AppendLine();
        sb.AppendLine("| Sensor | Location | Purpose |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine("| Chamber pressure transducer | Injector manifold tap | Compare to design Pc |");
        sb.AppendLine("| Fuel / ox feed pressure | Upstream of injector | Verify Δp |");
        sb.AppendLine("| Coolant inlet / outlet temperature | Regen manifolds | Verify Bartz estimate |");
        sb.AppendLine("| Thrust load cell | Engine mount | Compare to analytic + CFD |");
        sb.AppendLine("| High-speed video | Side view | Observe flame, instability |");
        sb.AppendLine("| Acoustic microphone | Near chamber | Detect chugging / screaming |");
        sb.AppendLine();
        sb.AppendLine("## Test sequence (physical ladder)");
        sb.AppendLine();
        sb.AppendLine("### Stage A — Water flow (no propellants)");
        sb.AppendLine("- Pump water through regen channels at design flow rate.");
        sb.AppendLine($"- Target coolant velocity ≈ {F(oTherm.CoolantVelocity, "F1")} m/s.");
        sb.AppendLine("- Pass: no leaks, Δp matches hydraulic estimate.");
        sb.AppendLine();
        sb.AppendLine("### Stage B — Cold flow (propellants, no ignition)");
        sb.AppendLine($"- Pressurize tanks to {F(f.FuelTankPressureBar, "F1")} bar.");
        sb.AppendLine($"- Open valves briefly; measure mass flow (bucket test / flow meter).");
        sb.AppendLine($"- Target: fuel {F(o.MassFlowFuel, "F3")} kg/s, ox {F(o.MassFlowOx, "F3")} kg/s.");
        sb.AppendLine("- Pass: flows within ±15% of analytic, stable injection pattern.");
        sb.AppendLine();
        sb.AppendLine("### Stage C — Hot fire (short burn)");
        sb.AppendLine($"- Duration: start with 1 s, then {F(f.BurnDurationS, "F1")} s if stable.");
        sb.AppendLine($"- Target thrust: {F(s.ThrustN, "F0")} N ± 15%");
        sb.AppendLine($"- Target Pc: {F(s.ChamberPressureBar, "F1")} bar ± 10%");
        sb.AppendLine($"- Max coolant outlet ΔT: {F(oTherm.CoolantTempRise, "F0")} K (Bartz estimate)");
        sb.AppendLine();
        sb.AppendLine("## Abort criteria (immediate shutdown)");
        sb.AppendLine();
        sb.AppendLine($"- Pc > {F(s.ChamberPressureBar * 1.25, "F1")} bar (25% overshoot)");
        sb.AppendLine("- Visible hard start or explosion on ignition");
        sb.AppendLine("- Acoustic instability (chugging/screech) growing in amplitude");
        sb.AppendLine("- Coolant outlet temperature rising faster than predicted");
        sb.AppendLine("- Any feed leak, fire outside chamber, or loss of remote control");
        sb.AppendLine();
        sb.AppendLine("## Pass / fail vs virtual predictions");
        sb.AppendLine();
        sb.AppendLine("| Quantity | Analytic target | Hot-fire pass band |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine($"| Thrust | {F(s.ThrustN, "F0")} N | ± 15% |");
        sb.AppendLine($"| Chamber pressure | {F(s.ChamberPressureBar, "F1")} bar | ± 10% |");
        sb.AppendLine($"| Mass flow (total) | {F(o.MassFlow, "F3")} kg/s | ± 15% |");
        sb.AppendLine($"| Specific impulse | {F(o.IspSeaLevelS, "F1")} s | ± 10% |");
        sb.AppendLine();
        sb.AppendLine("If hot-fire results fall outside these bands, **edit the spec**, re-run");
        sb.AppendLine("`design` + `test` + `validate`, and iterate — do not guess.");
        sb.AppendLine();
        sb.AppendLine("## After the first hot fire");
        sb.AppendLine();
        sb.AppendLine("1. Compare measured thrust, Pc, and Isp to `report.md` analytic + CFD tables.");
        sb.AppendLine("2. Inspect chamber/nozzle for erosion, coking, or cooling failure.");
        sb.AppendLine("3. Update the spec (O/F, Pc, cooling, expansion) based on measurements.");
        sb.AppendLine("4. Re-run the full virtual loop before the next physical test.");
        sb.AppendLine();

        return sb.ToString();
    }

    public static string BuildIterationLog(IterateOutcome oOut)
    {
        StringBuilder sb = new();
        sb.AppendLine($"# {oOut.FinalSpec.Name} — Auto-Iterate Log");
        sb.AppendLine();
        sb.AppendLine($"Generated by Impetus on {DateTime.Now:yyyy-MM-dd HH:mm}. " +
                      $"Source spec: `{oOut.OriginalSpec.Name}`.");
        sb.AppendLine();
        sb.AppendLine(oOut.Converged
            ? "**Result: CONVERGED** — all analytic gates pass. CFD (`test`) still required."
            : "**Result: NOT CONVERGED** — remaining failures cannot be fixed by spec changes (see below).");
        sb.AppendLine();
        sb.AppendLine("## Changes applied");
        sb.AppendLine();
        if (oOut.Steps.Count == 0)
            sb.AppendLine("None — no spec-level corrective rule was applicable.");
        else
        {
            sb.AppendLine("| Pass | Field | From | To | Reason |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (IterationStep oStep in oOut.Steps)
                sb.AppendLine($"| {oStep.Iteration} | `{oStep.Field}` | {oStep.From} | {oStep.To} | {oStep.Reason} |");
        }
        sb.AppendLine();
        sb.AppendLine("## Before / after");
        sb.AppendLine();
        sb.AppendLine("| Quantity | Original | Final |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine($"| O/F ratio | {F(oOut.OriginalSpec.OfRatio, "F2")} | {F(oOut.FinalSpec.OfRatio, "F2")} |");
        sb.AppendLine($"| Chamber pressure | {F(oOut.OriginalSpec.ChamberPressureBar, "F1")} bar | {F(oOut.FinalSpec.ChamberPressureBar, "F1")} bar |");
        sb.AppendLine($"| Cooling channels | {oOut.OriginalSpec.Cooling.Count} × Ø{F(oOut.OriginalSpec.Cooling.DiameterMM, "F1")} mm | {oOut.FinalSpec.Cooling.Count} × Ø{F(oOut.FinalSpec.Cooling.DiameterMM, "F1")} mm |");
        sb.AppendLine($"| Coolant dT | {F(oOut.OriginalThermal.CoolantTempRise, "F0")} K | {F(oOut.FinalThermal.CoolantTempRise, "F0")} K |");
        sb.AppendLine($"| Throat heat flux | {F(oOut.OriginalThermal.ThroatHeatFlux / 1e6, "F1")} MW/m2 | {F(oOut.FinalThermal.ThroatHeatFlux / 1e6, "F1")} MW/m2 |");
        sb.AppendLine($"| Isp (design ambient) | {F(oOut.OriginalDesign.IspSeaLevelS, "F1")} s | {F(oOut.FinalDesign.IspSeaLevelS, "F1")} s |");
        sb.AppendLine();
        sb.AppendLine("## Final virtual checks");
        sb.AppendLine();
        sb.AppendLine("| Check | Status | Detail |");
        sb.AppendLine("|---|---|---|");
        foreach (ValidationCheck oCheck in oOut.FinalValidation.Checks)
            sb.AppendLine($"| {oCheck.Name} | {StatusLabel(oCheck.Status)} | {oCheck.Detail} |");
        sb.AppendLine();
        if (oOut.Unfixable.Count > 0)
        {
            sb.AppendLine("## Not fixable from the spec");
            sb.AppendLine();
            foreach (string strNote in oOut.Unfixable)
                sb.AppendLine($"- {strNote}");
            sb.AppendLine();
        }
        if (oOut.PropellantWhatIf.Count > 0)
        {
            sb.AppendLine("## Propellant what-if (same thrust & Pc, nominal O/F)");
            sb.AppendLine();
            sb.AppendLine("| Pair | Coolant dT | Gate (per-fuel limit) |");
            sb.AppendLine("|---|---|---|");
            foreach (PropellantOption oOpt in oOut.PropellantWhatIf)
                sb.AppendLine($"| `{oOpt.Key}` | {F(oOpt.CoolantRiseK, "F0")} K | {(oOpt.PassesGate ? "PASS" : "fail")} |");
            sb.AppendLine();
        }
        sb.AppendLine("## Next steps");
        sb.AppendLine();
        if (oOut.Converged)
        {
            sb.AppendLine($"1. `dotnet run --project src/Impetus -- design specs/{oOut.FinalSpec.Name}.json` — geometry + STL");
            sb.AppendLine($"2. `dotnet run --project src/Impetus -- test specs/{oOut.FinalSpec.Name}.json` — CFD virtual test");
            sb.AppendLine("3. Read `report.md` and `hotfire-plan.md` before any physical work.");
        }
        else
        {
            sb.AppendLine("The remaining failures are model- or scale-level, not spec-level:");
            sb.AppendLine();
            sb.AppendLine("- Film-cooling / 1D regen solver — roadmap §8.3");
            sb.AppendLine("- Propellant change — see what-if table above");
            sb.AppendLine("- Larger thrust class — better volume-to-surface ratio eases cooling");
        }
        sb.AppendLine();
        return sb.ToString();
    }

    public static void PrintSummary(ValidationResult oVal)
    {
        Console.WriteLine($"  == Virtual validation: {oVal.Verdict} ==");
        foreach (ValidationCheck oCheck in oVal.Checks)
        {
            string strMark = oCheck.Status switch
            {
                CheckStatus.Pass => "OK ",
                CheckStatus.Warn => "WARN",
                CheckStatus.Fail => "FAIL",
                _ => "???",
            };
            Console.WriteLine($"    [{strMark}] {oCheck.Name}");
        }
        Console.WriteLine($"  {oVal.VerdictSummary}");
        Console.WriteLine();
    }

    static string StatusLabel(CheckStatus e) => e switch
    {
        CheckStatus.Pass => "PASS",
        CheckStatus.Warn => "WARN",
        CheckStatus.Fail => "FAIL",
        _ => "?"
    };

    static string F(double f, string strFmt) => f.ToString(strFmt, CultureInfo.InvariantCulture);
    static string MM(double fMeters) => F(fMeters * 1000.0, "F1");
}
